    sys.exit(loop.run_until_complete(main()))
  File "/home/mal/.local/lib/python3.10/site-packages/asyncqt/__init__.py", line 309, in run_until_complete
    return future.result()
  File "/home/mal/libraries/i3tree/17.py", line 427, in main
    await i3.main()
  File "/home/mal/.local/lib/python3.10/site-packages/i3ipc/aio/connection.py", line 664, in main
    await self._main_future
  File "/home/mal/.local/lib/python3.10/site-packages/i3ipc/aio/connection.py", line 34, in handler_coroutine
    await handler(conn, data)
  File "/home/mal/libraries/i3tree/17.py", line 244, in updatetree
    tree = await i3.get_tree()
  File "/home/mal/.local/lib/python3.10/site-packages/i3ipc/aio/connection.py", line 589, in get_tree
    return Con(json.loads(data), None, self)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 36495 (char 36494)
